import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import useAuth from '@/hooks/useAuth';
import useSubscription from '@/hooks/useSubscription';
import { getProducts, Product } from '@stripe/firestore-stripe-payments';
import payments from '@/lib/stipe';
import { GetStaticProps } from 'next';
import Membership from '@/components/Membership';

interface AccountProps {
  products: Product[]
}

function Account({ products }: AccountProps) {
  const { user, logout } = useAuth();
  const subscription = useSubscription(user);

  return (
    <div>
      <Head>
        <title>Account - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <header>
        <Link href="/">
          <img
            width={120}
            height={120}
            src='https://rb.gy/ulxxee'
            alt="Logo da empresa - Netflix"
            className='cursor-pointer object-contain'
          />
        </Link>
        <Link href="/account">
          <img
            alt="avatar do usuário"
            src='https://rb.gy/g1pwyx'
            className='cursor-pointer rounded'
          />
        </Link>
      </header>

      <main className='mx-auto max-w-6xl px-5 pt-24 pb-12 transition-all md:px-10'>
        <div className='flex flex-col gap-x-4 md:flex-row md:items-center'>
          <h1 className='text-3xl md:text-4xl'>Account</h1>
          <div className='-ml-0.5 flex items-center gap-x-1.5'>
            <img src='https://rb.gy/4vfk4r' alt="" className='h-7 w-7' />
            <p className='text-xs font-semibold text-[#555]'>
              Member since {subscription?.created}
            </p>
          </div>
        </div>

        <Membership />

        <div className='mt-6 grid grid-cols-1 gap-x-4 border px-4 py-4 md:grid-cols-4 md:border-x-0 md:border-t md:border-b-0 md:px-0 md:pb-0'>
          <h4 className='text-lg text-[gray]'>Plan Details</h4>
          {/* Find the current plan */}
          <div className='col-span-2 font-medium'>
            {products?.filter(
              (product) => product.id === subscription?.product)[0]?.name
            }
          </div>
          <p className='cursor-pointer text-blue-500 hover:underline md:text-right'>
            Change plan
          </p>
        </div>

        <div className='mt-6 grid grid-cols-1 gap-x-4 border px-4 py-4 md:grid-cols-4 md:border-x-0 md:border-t md:border-b-0 md:px-0 md:pb-0'>
          <h4>
            Settings
          </h4>
          <p
            onClick={logout}
            className='col-span-3 cursor-pointer text-blue-500 hover:underline'
          >
            Sign out all devices
          </p>
        </div>
      </main>
    </div>
  )
}

export default Account

export const getStaticProps: GetStaticProps = async () => {
  const products = await getProducts(payments, {
    includePrices: true,
    activeOnly: true,
  })
    .then((response) => response)
    .catch((err) => console.log(err.message)
    );

  return {
    props: {
      products,
    }
  }
}