import React, { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import useAuth from '@/hooks/useAuth';
import { AiOutlineCheck } from 'react-icons/ai';
import { Product } from '@stripe/firestore-stripe-payments';
import Table from './Table';
import Loader from './Loader';
import { loadCheckout } from '@/lib/stipe';

interface PlansProps {
  products: Product[];
}

function Plans({ products }: PlansProps) {

  const { logout, user } = useAuth();
  const [isBillingLoading, setIsBillingLoading] = useState(false);
  const [selectedPlan, setSelectedPlan] = useState<Product | null>(products[2]);

  function subscribeToPlan() {
    if (!user) return;

    loadCheckout(selectedPlan?.prices[0].id!)
    setIsBillingLoading(true)
  }

  return (
    <div>
      <Head>
        <title>Plans - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <header className='border-b border-white/10 bg-[#141414]'>
        <Link href="/">
          <img
            width={100}
            height={100}
            src="https://rb.gy/ulxxee"
            alt="Logo da empresa - Netflix"
            className='cursor-pointer object-contain'
          />
        </Link>
        <button
          onClick={logout}
          className="text-lg font-medium hover:underline"
        >
          Sign Out
        </button>
      </header>

      <main className='mx-auto max-w-5xl px-5 mt-28 pb-12 transition-all md:px-10'>
        <h1 className="mb-3 text-3xl font-medium">
          Choose the plan that is right for you
        </h1>
        <ul>
          <li className="flex items-center gap-x-2 text-lg">
            <AiOutlineCheck className="h-7 w-7 text-[#E50914]" />
            Watch all you want. Ad-free.</li>
          <li className="flex items-center gap-x-2 text-lg">
            <AiOutlineCheck className="h-7 w-7 text-[#E50914]" />
            Recommendations jus for you.</li>
          <li className="flex items-center gap-x-2 text-lg">
            <AiOutlineCheck className="h-7 w-7 text-[#E50914]" />
            Change or cancel your plan anytime.</li>
        </ul>

        <div className='mt-4 flex flex-col space-y-4'>
          <div className='flex w-full items-center justify-center self-end md:w-3/5'>
            {products?.map((product) => (
              <div
                key={product.id}
                onClick={() => setSelectedPlan(product)}
                className={`planBox ${selectedPlan?.id === product.id ? 'opacity-100' : 'opacity-60'}`}
              >
                {product.name}
              </div>
            ))}

          </div>

          <Table products={products} selectedPlan={selectedPlan} />

          <button
            onClick={subscribeToPlan}
            disabled={!selectedPlan || isBillingLoading}
            className={`mx-auto w-11/12 rounded bg-[#E50914] py-4 text-xl shadow hover:bg-[#f6121d] md:w-[420px] ${isBillingLoading && 'opacity-60'}`}
          >
            {isBillingLoading ? (
              <Loader color='dark:fill-gray-300' />
            ) : (
              'Subscribe'
            )}
          </button>
        </div>
      </main>
    </div>
  )
}

export default Plans
